config/routes.rb
TeclaCultura::Application.routes.draw do      
	
  mount Ckeditor::Engine => '/ckeditor'

  get "home/index"

	namespace :mobile_app do   
		resources :info_pages, :only=>[:show,:index]
		resources :places, :only=>[:show,:index]
		get "map" => "places#map", :as=>"places_map_location"
		resources :place_types, :only=>[:show,:index]
		resources :galleries, :only=>[:show,:index]
		resources :events, :only=>[:show,:index]
		post "event/:event_id/attend/" => "events#attend", :as => "attend_event"
		root :to => "home#index"
	end
     
	match 'auth/:provider/callback', to: 'sessions#create'
	match 'auth/failure', to: redirect('/')
	scope "mobile_app" do
		get "sign_in" => "sessions#new",  as: "mobile_sign_in"
	  	delete 'sign_out', to: 'sessions#destroy', as: 'mobile_sign_out'
	end
	scope "admin" do
		get "sign_in" => "sessions#new"
	  	get 'sign_out', to: 'sessions#destroy', as: 'sign_out'
	end
	                             
	root :to =>"mobile_app/home#index"
	namespace :admin do   
	  root :to =>"events#index"
	  resources :photos, :only => [:new,:create,:show,:destroy]
	  post "photos/multiple/:id" =>  "photos#multiple_create", as: "multiple_photos"   
	  resources :galleries 
	  resources :events    
	  resources :info_pages
	  resources :places    
	  resources :place_types
	end
  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  cattr_accessor :current_user
  attr_accessible :description, :picture_file, :gallery_id
  belongs_to :gallery
  mount_uploader :picture_file, PhotoUploader
  before_destroy do |photo|
    photo.remove_picture_file
  end

  def default_name
    id.to_s
  end

  def file_path
  	picture_file.url
  end

  protected
  
  def upload_to_facebook
  	unless  gallery.nil?
  		current_user.upload_photo(self)
  	end
  end
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < ApplicationController
  before_filter :load_gallery
  # GET /photos
  # GET /photos.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new
    @multiple = params[:multiple] == "true"

    respond_to do |format|
      if @multiple
        format.html { render :partial=> "admin/galleries/upload_photos_step", :layout=>!@multiple}
      else
        format.html #normal
      end
      format.json { render json: @photo }
    end
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])
    respond_to do |format|
      if @photo.save
        @current_user.upload_photo(@photo)
        format.html { redirect_to edit_admin_gallery_path(:id=>@gallery.id), notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def multiple_create
    @photo = Photo.new(params[:photo])
    @photo.gallery_id = @gallery.id
    if @photo.save
      @current_user.delay.upload_photo(@photo)
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to edit_admin_gallery_path(:id=>@gallery.id) }
      format.json { render :json => true }
    end
  end

  def load_gallery
    print "\nparams.nil?=>#{params}\n"
    if !params[:gallery_id].nil? or  !params[:photo].nil? 
      gallery_id = params[:gallery_id] || params[:photo][:gallery_id]
      @gallery = Gallery.find_by_id(gallery_id)
    end
  end
end

app/views/admin/photos/_form.html.erb
<%- action = new_or_edit ? admin_info_pages_path : admin_info_page_path(:id=>@info_page.id) %>
<%= form_for @photo, :url=>action,:html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'short-text-area',:rows=>5 %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :picture_file, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :picture_file, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :gallery_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :gallery_id, Gallery.all, :id, :name%>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_photos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/photos/_photo.html.erb
<div class = "photo-display">
	<p><%= image_tag photo.picture_file.thumb %></p>
	<div class ="actions">
	  <%= link_to admin_photo_path(:id=>photo.id,:gallery_id=>@gallery.id), :confirm => 'Are you sure?', :method => :delete,:class=>"btn btn-danger" do %>
	  	<i class="icon-remove-sign icon-white"></i> Eliminar
	  <%end%>
	</div>
</div>

app/views/admin/photos/edit.html.erb
<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form', :locals => {:new_or_edit=>false} %>

app/views/admin/photos/index.html.erb
<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:file) %></th>
      <th><%= model_class.human_attribute_name(:gallery_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= link_to photo.id, admin_photo_path(photo) %></td>
        <td><%= photo.description %></td>
        <td><%= photo.file %></td>
        <td><%= photo.gallery_id %></td>
        <td><%=l photo.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_photo_path(photo), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_photo_path(photo),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_photo_path,
            :class => 'btn btn-primary' %>

app/views/admin/photos/multiple_create.js.erb
<% if @photo.new_record? %>
  alert("Failed to upload painting: <%= j @photo.errors.full_messages.join(', ').html_safe %>");
<% else %>
  //console.log("<%= debug @photo %>")
  $("#photos").append("<%= j render(@photo) %>");
<% end %>

app/views/admin/photos/new.html.erb
<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form', :locals => {:new_or_edit=>true} %>

app/views/admin/photos/show.html.erb
<%=image_tag @photo.picture_file.thumb%>