config/routes.rb
TeclaCultura::Application.routes.draw do      
	
  mount Ckeditor::Engine => '/ckeditor'

  get "home/index"

	namespace :mobile_app do   
		resources :info_pages, :only=>[:show,:index]
		resources :places, :only=>[:show,:index]
		get "map" => "places#map", :as=>"places_map_location"
		resources :place_types, :only=>[:show,:index]
		resources :galleries, :only=>[:show,:index]
		resources :events, :only=>[:show,:index]
		post "event/:event_id/attend/" => "events#attend", :as => "attend_event"
		root :to => "home#index"
	end
     
	match 'auth/:provider/callback', to: 'sessions#create'
	match 'auth/failure', to: redirect('/')
	scope "mobile_app" do
		get "sign_in" => "sessions#new",  as: "mobile_sign_in"
	  	delete 'sign_out', to: 'sessions#destroy', as: 'mobile_sign_out'
	end
	scope "admin" do
		get "sign_in" => "sessions#new"
	  	get 'sign_out', to: 'sessions#destroy', as: 'sign_out'
	end
	                             
	root :to =>"mobile_app/home#index"
	namespace :admin do   
	  root :to =>"events#index"
	  resources :photos, :only => [:new,:create,:show,:destroy]
	  post "photos/multiple/:id" =>  "photos#multiple_create", as: "multiple_photos"   
	  resources :galleries 
	  resources :events    
	  resources :info_pages
	  resources :places    
	  resources :place_types
	end
  

end

app/controllers/mobile_app/events_controller.rb
class MobileApp::EventsController < MobileApp::MobileController

  def index
    @selected = "hour-range-selected"
    @calendar = !params[:calendar].nil?
    if params[:month]
      @date_for_calendar = Date.parse(params[:month])
      @events = Event.grouped_events_by_day(@date_for_calendar)
      @up_comming = Event.up_coming_events
          
    elsif params[:date_at]
      @date_at = Date.parse(params[:date_at])
      @events = Event.on_day(@date_at)
    else
      @date_for_calendar = Date.today
      @events = Event.grouped_events_by_day(@date_for_calendar)
      @up_comming = Event.up_coming_events
    end 
  	
  	respond_to do |format|
      if @date_at
        format.html{ render "date_index"}
        format.mobile{ render "date_index"} 
      elsif @calendar
  		  format.html{ render :partial=>"calendar",:layout=>false}
  		  format.mobile{ render :partial=>"calendar",:layout=>false}
      else
        format.html
        format.mobile
  		end
      #format.json { json: { events: @events, date_for_calendar: @date_for_calendar}}
  	end
  end

  def show
  	@event = Event.find_by_id(params[:id])
  	respond_to do |format|
  		format.html
  		format.mobile
  		#format.json { json: {event: @event} }
  	end
  end

  def attend
    if current_user_signed_in?
      print "\nSending to fb from events controller\n"
      @attended = @current_user.attend_to(params[:event_id])
      @logged = true
      session[:login_for_mobile] = false
      session[:attending_event] = nil
    else
      print "\nFail sending to fb from events controller\n"
      @attended = false
      @logged = false
      session[:login_for_mobile] = true
      session[:attending_event] = params[:event_id]
    end
    respond_to do |format|
      format.html
      format.mobile
      format.json { render :json => {attended: @attended, logged: @logged}.to_json }
    end
  end
end

app/controllers/mobile_app/galleries_controller.rb
class MobileApp::GalleriesController < MobileApp::MobileController
  def index
  	@galleries_groups = Gallery.all.each_slice(4).to_a
  	@grid_columns = ["ui-block-a","ui-block-b","ui-block-c","ui-block-d"]
  	print "\n#{@galleries_groups.to_yaml}\n"
  end

  def show
  	@gallery = Gallery.find_by_id(params[:id])
  end
end

app/controllers/mobile_app/home_controller.rb
class MobileApp::HomeController < MobileApp::MobileController
  def index
  end
end

app/controllers/mobile_app/info_pages_controller.rb
class MobileApp::InfoPagesController < MobileApp::MobileController
  def index
  	@pages = InfoPage.all
  end

  def show
  	@page = InfoPage.find(params[:id])
  end
end

app/controllers/mobile_app/mobile_controller.rb
class MobileApp::MobileController < ApplicationController
	layout :load_layout
	before_filter :set_mobile_format

	def set_mobile_format
		request.format = :mobile unless request.format == :json
	end

	def load_layout
		params[:layout]=="true" ? "mobile_app" : false
	end

	
end

app/controllers/mobile_app/place_types_controller.rb
class MobileApp::PlaceTypesController < MobileApp::MobileController
  def index
  	@place_types = PlaceType.all
  end
end

app/controllers/mobile_app/places_controller.rb
class MobileApp::PlacesController < MobileApp::MobileController
	before_filter :load_type
  def index
  	print "\n!@type.nil? on index=>#{!@type.nil?}\n"
  	@places = !@type.nil? ? Place.actives.where(:place_type_id=>@type.id) : Place.all
  end

  def show      
		@place = Place.find_by_id(params[:id])
  end

  def load_type
  	@type = PlaceType.find_by_id(params[:place_type_id])
  	print "\n@type.nil?=>#{@type.nil?}\n"
  end

  def map
    @places = Place.places_for_map
    respond_to do |format|
      format.html
      format.mobile
      format.json{ render json: @places}
    end
  end

end

app/helpers/mobile_app/events_helper.rb
module MobileApp::EventsHelper
	def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).calendar_with_header
  end

  def calendar_weeks(date = Date.today, &block)
    Calendar.new(self, date, block).week_rows
  end

  def new_calendar(date = Date.today, &block)
    Calendar.new(self, date, block)
  end


  def link_for_event
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER_SHORT = %w[Dom Lun Mar Mie Jue Vie Sab]
    HEADER_LONG = %w[Domingo Lunes Martes Miercoles Jueves Viernes Sabado]
    START_DAY = :sunday

    delegate :content_tag, :link_to, :mobile_app_events_url ,to: :view

    def calendar_with_header
    	content_tag :div, class: "calendar-body" do
    		table_with_headers
    	end
    end

    def table_with_headers
      content_tag :table, class: "calendar-days" do
        table_headers + table_body
      end
    end

    def table_headers
      content_tag :thead do
        header_long + header_short
      end
    end

    def table_body
      content_tag :tbody, class: "week-rows", :id=>"week-rows" do
        week_rows
      end
    end

     def header_long
      content_tag :tr, class: "calendar-header calendar-header-long",:data=>{:role=>"header"} do
        HEADER_LONG.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def header_short
      content_tag :tr,class: "calendar-header calendar-header-short",:data=>{:role=>"header"} do
        HEADER_SHORT.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell_link(day)
      if day.month != date.month
        content_tag :div, class: "day-buttom" do
          view.capture(day, &callback)
        end
      else
        link_to "#events-date", :data=>{:backend=>mobile_app_events_url(:date_at=>day)}, :class=>"day-link backend-link" do
          content_tag :div, class: "day-buttom day-buttom-link" do
            view.capture(day, &callback)
          end
        end
      end
    end

    def day_cell(day)
        content_tag :td, class: day_classes(day) do
          day_cell_link(day)
        end
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/helpers/mobile_app/galleries_helper.rb
module MobileApp::GalleriesHelper
end

app/helpers/mobile_app/home_helper.rb
module MobileApp::HomeHelper
end

app/helpers/mobile_app/info_pages_helper.rb
module MobileApp::InfoPagesHelper
end

app/helpers/mobile_app/place_types_helper.rb
module MobileApp::PlaceTypesHelper
end

app/helpers/mobile_app/places_helper.rb
module MobileApp::PlacesHelper
end

app/views/mobile_app/home/index.html.erb
<ul data-role="listview" data-inset="false" data-theme="b">
	  <li>
	  	<%=link_to mobile_app_place_types_path do %>
	  		<%=image_tag "/images/album-bb.jpg" %>
	  		<h3>Escondites</h3>
	      <p>Lugares que puedes visitar</p>
	  	<%end%>
	  </li>

	  <li>
	    <%=link_to mobile_app_galleries_path do%>
	      <img src="/images/album-bb.jpg" />
	      <h3>Galeria</h3>
	      <p>Fotos de eventos</p>
	    <%end%>
	  </li>

	  <li>
	    <a href="#map-page">
	      <img src="/images/album-bb.jpg" />
	      <h3>Mapa</h3>
	      <p>Puntos de cultura en Santa Tecla</p>
	    </a>
	  </li>

	  <li>
	  	<%=link_to mobile_app_events_path do %>
	  		<img src="/images/album-bb.jpg" />
	    	<h3>Agenda Cultural</h3>
	    	<p>No te pierdas los proximos eventos culturales</p>
	  	<%end%>
	    
	  </li>

	  <li>
	    <a href="index.html">
	      <img src="/images/album-bb.jpg" />
	      <h3>Info</h3>
	      <p>Información acerca de Santa Tecla</p>
	    </a>
	  </li>

	  <li>
	    <a href="index.html">
	      <img src="/images/album-bb.jpg" />
	      <h3>Favoritos</h3>
	      <p>Tus Lugares favoritos</p>
	    </a>
	  </li>

	</ul>

app/views/mobile_app/home/index.mobile.erb
<div data-role= "content">
	<h1>Bienvenido</h1>
	<div class="ui-grid-a">
		<div class="ui-block-a">
			<%=link_to mobile_app_events_path, :class=>"menu-link" do %>
				<center>
					<h3>Agenda Cultural</h3>
					<%=image_tag "/images/icons/calendar.png", :class=>"menu-icon" %>
				</center>
			<%end%>
		</div>
		<div class="ui-block-b">
			<%=link_to mobile_app_place_types_path, :class=>"menu-link" do %>
				<center>
					<h3>Escondites</h3>
					<%=image_tag "/images/icons/places.png", :class=>"menu-icon" %>
				</center>
			<%end%>
		</div>
		<div class="ui-block-a">
			<%=link_to  mobile_app_info_pages_path, :class=>"menu-link" do %>
				<center>
					<h3>Información</h3>
					<%=image_tag "/images/icons/info_pages.png", :class=>"menu-icon" %>
				</center>
			<%end%>
		</div>
		
		<div class="ui-block-b">
			<%=link_to mobile_app_galleries_path, :class=>"menu-link" do%>
				<center>
					<h3>Galeria</h3>
					<%=image_tag "/images/icons/gallery.png", :class=>"menu-icon" %>
				</center>
			<%end%>
		</div>	
	</div>
	<div class="ui-grid-solo">
		<div class="ui-block-a">
	    	<a href="#map-page" class = "menu-link">
				<center>
					<h3>Mapa</h3>
					<%=image_tag "/images/icons/map.png", :class=>"menu-icon" %>
				</center>
			</a>
		</div>
	</div>
	
 </div>