config/routes.rb
TeclaCultura::Application.routes.draw do      
	
  mount Ckeditor::Engine => '/ckeditor'

  get "home/index"

	namespace :mobile_app do   
		resources :info_pages, :only=>[:show,:index]
		resources :places, :only=>[:show,:index]
		get "map" => "places#map", :as=>"places_map_location"
		resources :place_types, :only=>[:show,:index]
		resources :galleries, :only=>[:show,:index]
		resources :events, :only=>[:show,:index]
		post "event/:event_id/attend/" => "events#attend", :as => "attend_event"
		root :to => "home#index"
	end
     
	match 'auth/:provider/callback', to: 'sessions#create'
	match 'auth/failure', to: redirect('/')
	scope "mobile_app" do
		get "sign_in" => "sessions#new",  as: "mobile_sign_in"
	  	delete 'sign_out', to: 'sessions#destroy', as: 'mobile_sign_out'
	end
	scope "admin" do
		get "sign_in" => "sessions#new"
	  	get 'sign_out', to: 'sessions#destroy', as: 'sign_out'
	end
	                             
	root :to =>"mobile_app/home#index"
	namespace :admin do   
	  root :to =>"events#index"
	  resources :photos, :only => [:new,:create,:show,:destroy]
	  post "photos/multiple/:id" =>  "photos#multiple_create", as: "multiple_photos"   
	  resources :galleries 
	  resources :events    
	  resources :info_pages
	  resources :places    
	  resources :place_types
	end
  

end

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TeclaCultura" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <%if current_user_signed_in?%>
      <div class="navbar navbar-fluid-top navbar-inverse">
        <div class="navbar-inner">
          <div class="container-fluid">
            <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <%=link_to "Tecla Cultura", root_path, :class=>"brand"%>
            <div class="container-fluid nav-collapse">
              <ul class="nav">
                <li class="dropdown">
                  <%=link_to "", :class=>"dropdown-toggle", :data=>{:toggle=>"dropdown"} do%>
                    Eventos
                    <b class="caret"></b>
                  <%end%>
                  <ul class="dropdown-menu">
                    <li><%=link_to "Todos los eventos", events_path%></li>
                    <li><%=link_to "Nuevo Evento", new_event_path%></li>
                  </ul>
                </li>
                
                <li class="dropdown">
                  <%=link_to "", :class=>"dropdown-toggle", :data=>{:toggle=>"dropdown"} do%>
                    Establecimientos
                    <b class="caret"></b>
                  <%end%>
                  <ul class="dropdown-menu">
                    <li><%=link_to "Todos los Establecimientos", places_path%></li>
                    <li><%=link_to "Nuevo Establecimiento", new_place_path%></li>
                     <li><%=link_to "Tipos de Establecimientos", place_types_path %>
                    <li><%=link_to "Nuevo Tipo de EStablecimiento", new_place_type_path %>
                  </ul>
                </li>


                <li class="dropdown">
                  <%=link_to "", :class=>"dropdown-toggle", :data=>{:toggle=>"dropdown"} do%>
                    Galerias
                    <b class="caret"></b>
                  <%end%>
                  <ul class="dropdown-menu">
                    <li><%=link_to "Todos las galerias", galleries_path%></li>
                    <li><%=link_to "Nueva galería", new_gallery_path%></li>
                    <li><%=link_to "Agregar Nueva Fotografía", new_photo_path%>
                  </ul>
                </li>

                <li class="dropdown">
                  <%=link_to "", :class=>"dropdown-toggle", :data=>{:toggle=>"dropdown"} do%>
                    Paginas informativas
                    <b class="caret"></b>
                  <%end%>
                  <ul class="dropdown-menu">
                    <li><%=link_to "Todas las paginas informativas", info_pages_path%></li>
                    <li><%=link_to "Nuevo Pagina Informativa", new_info_page_path%></li>
                  </ul>
                </li>

              </ul>
               <ul class="nav pull-right">
                   <li><%= link_to "Cerrar session" , sign_out_path %></li>
               </ul>
            </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>
    <%end%>

    <div class="container-fluid">
      <div class="row-fluid">
        <%if current_user_signed_in?%>
          <div class="span3">
            <div class="well sidebar-nav">
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "#{current_user_signed_in?}", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        <%end%>
        <%- yield_span = current_user_signed_in? ? "span9" : "span12"%>
        <div class="<%=yield_span%>">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer class ="navbar-fixed-bottom">
        <p>&copy; </p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>