config/routes.rb
TeclaCultura::Application.routes.draw do      
	
  mount Ckeditor::Engine => '/ckeditor'

  get "home/index"

	namespace :mobile_app do   
		resources :info_pages, :only=>[:show,:index]
		resources :places, :only=>[:show,:index]
		get "map" => "places#map", :as=>"places_map_location"
		resources :place_types, :only=>[:show,:index]
		resources :galleries, :only=>[:show,:index]
		resources :events, :only=>[:show,:index]
		post "event/:event_id/attend/" => "events#attend", :as => "attend_event"
		root :to => "home#index"
	end
     
	match 'auth/:provider/callback', to: 'sessions#create'
	match 'auth/failure', to: redirect('/')
	scope "mobile_app" do
		get "sign_in" => "sessions#new",  as: "mobile_sign_in"
	  	delete 'sign_out', to: 'sessions#destroy', as: 'mobile_sign_out'
	end
	scope "admin" do
		get "sign_in" => "sessions#new"
	  	get 'sign_out', to: 'sessions#destroy', as: 'sign_out'
	end
	                             
	root :to =>"mobile_app/home#index"
	namespace :admin do   
	  root :to =>"events#index"
	  resources :photos, :only => [:new,:create,:show,:destroy]
	  post "photos/multiple/:id" =>  "photos#multiple_create", as: "multiple_photos"   
	  resources :galleries 
	  resources :events    
	  resources :info_pages
	  resources :places    
	  resources :place_types
	end
  

end

app/models/event.rb
class Event < ActiveRecord::Base
  cattr_accessor :current_user
  attr_accessible :cover, :date_at, :description, :flayer, :name, :place_id, :state,:start_at, :address,:map_zoom, :map_latlng
  has_many :galleries
  belongs_to :place
  mount_uploader :flayer, EventCoverUploader
  def location
  	place.nil? ? address : place.location
  end
  def date_for_fb
  	date_at+6.hours
  end

  def changes_to_fb
    changes_fb = Hash.new
    self.changes.each do |k,v|
      case k
        when "flayer"
          changes_fb[:picture] = v.last
        when "date_at"
          changes_fb[:start_time] = v.last
        when "place_id", "address"
          changes_fb[:location] = location
        when "name", "description"
          changes_fb[k.to_sym] = v.last
      end
    end
    return changes_fb
  end

  def latlng
    if place.nil?
      map_latlng unless map_latlng.nil?
    else
      place.map_latlng
    end 
  end

  def lat
    if place.nil?
      map_latlng.delete("(").delete(")").strip.split(",")[0] unless map_latlng.nil?
    else
      place.lat
    end
  end

  def lng
    if place.nil?
      map_latlng.delete("(").delete(")").strip.split(",")[1] unless map_latlng.nil?
    else
      place.lng
    end
  end

  def zoom
    self.map_zoom.blank? ? 15 : self.map_zoom
  end

  def self.on_day(date)
    Event.where(:date_at=>(date.beginning_of_day..date.end_of_day )).order(:start_at)
  end

  def self.grouped_events_by_day(date)
    hash = Hash.new
    Event.where(:date_at=>(date.beginning_of_month..date.end_of_month )).order(:start_at).each do |event|
      if !hash.has_key?(event.start_at.day.to_i.to_s.to_sym)
        hash[event.start_at.day.to_i.to_s.to_sym]={ event.start_at.hour.to_i.to_s.to_sym=>event}
      else
        hash[event.start_at.day.to_i.to_s.to_sym][event.start_at.hour.to_i.to_s.to_sym] = event
      end
    end
    return hash
  end

  def on_day(date)
    Event.where(:date_at=>(date.beginning_of_day..date.end_of_day )).order(:start_at)
  end

  def self.up_coming_events
    hash = Hash.new
    date = Date.today
    Event.where(:date_at=>(date..date.end_of_month )).order(:start_at).limit(3).each do |event|
      if !hash.has_key?(event.start_at.day.to_i.to_s.to_sym)
        hash[event.start_at.day.to_i.to_s.to_sym]=[event]
      else
        hash[event.start_at.day.to_i.to_s.to_sym] << event
      end
    end
    return hash
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    @show_place = "show-place"
    @show_address = "hidden-place"
    @toogle_map = -1
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
    @show_place = @event.place.nil? ? "hidden-place" : "show-place"
    @show_address =  @event.address.nil? ? "hidden-place" : "show-place"
    @toogle_map = @event.map_latlng.nil? ? -1 : 1
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])
    @event.date_at = DateTime.parse("#{params[:event][:date_at]} #{params[:event][:start_at]} -0600")
    @event.start_at = DateTime.parse("#{params[:event][:date_at]} #{params[:event][:start_at]} -0600")
    respond_to do |format|
      if @event.save
        @current_user.delay.create_fb_event(@event) if @current_user.is_admin
        format.html { redirect_to admin_events_path, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])
    params[:event][:date_at] = DateTime.parse("#{params[:event][:date_at]} #{params[:event][:start_at]} -0600")
    params[:event][:start_at] = DateTime.parse("#{params[:event][:date_at]} #{params[:event][:start_at]} -0600")
    @event.assign_attributes(params[:event])
    print "\ncambios en el objeto=>#{@event.changes}\n"
    changes = @event.changes_to_fb
    print "\nchanges_to_fb antes de guardar=>#{changes}\n"
    respond_to do |format|
      if @event.save
        change_to_fb = @current_user.delay.update_fb_event(@event,changes) if !changes.empty?
        print "\nSe cambio el de facebook=>#{change_to_fb}\n"
        format.html { redirect_to admin_events_path, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to admin_events_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/mobile_app/events_controller.rb
class MobileApp::EventsController < MobileApp::MobileController

  def index
    @selected = "hour-range-selected"
    @calendar = !params[:calendar].nil?
    if params[:month]
      @date_for_calendar = Date.parse(params[:month])
      @events = Event.grouped_events_by_day(@date_for_calendar)
      @up_comming = Event.up_coming_events
          
    elsif params[:date_at]
      @date_at = Date.parse(params[:date_at])
      @events = Event.on_day(@date_at)
    else
      @date_for_calendar = Date.today
      @events = Event.grouped_events_by_day(@date_for_calendar)
      @up_comming = Event.up_coming_events
    end 
  	
  	respond_to do |format|
      if @date_at
        format.html{ render "date_index"}
        format.mobile{ render "date_index"} 
      elsif @calendar
  		  format.html{ render :partial=>"calendar",:layout=>false}
  		  format.mobile{ render :partial=>"calendar",:layout=>false}
      else
        format.html
        format.mobile
  		end
      #format.json { json: { events: @events, date_for_calendar: @date_for_calendar}}
  	end
  end

  def show
  	@event = Event.find_by_id(params[:id])
  	respond_to do |format|
  		format.html
  		format.mobile
  		#format.json { json: {event: @event} }
  	end
  end

  def attend
    if current_user_signed_in?
      print "\nSending to fb from events controller\n"
      @attended = @current_user.attend_to(params[:event_id])
      @logged = true
      session[:login_for_mobile] = false
      session[:attending_event] = nil
    else
      print "\nFail sending to fb from events controller\n"
      @attended = false
      @logged = false
      session[:login_for_mobile] = true
      session[:attending_event] = params[:event_id]
    end
    respond_to do |format|
      format.html
      format.mobile
      format.json { render :json => {attended: @attended, logged: @logged}.to_json }
    end
  end
end

app/controllers/mobile_app/galleries_controller.rb
class MobileApp::GalleriesController < MobileApp::MobileController
  def index
  	@galleries_groups = Gallery.all.each_slice(4).to_a
  	@grid_columns = ["ui-block-a","ui-block-b","ui-block-c","ui-block-d"]
  	print "\n#{@galleries_groups.to_yaml}\n"
  end

  def show
  	@gallery = Gallery.find_by_id(params[:id])
  end
end

app/controllers/mobile_app/home_controller.rb
class MobileApp::HomeController < MobileApp::MobileController
  def index
  end
end

app/controllers/mobile_app/info_pages_controller.rb
class MobileApp::InfoPagesController < MobileApp::MobileController
  def index
  	@pages = InfoPage.all
  end

  def show
  	@page = InfoPage.find(params[:id])
  end
end

app/controllers/mobile_app/mobile_controller.rb
class MobileApp::MobileController < ApplicationController
	layout :load_layout
	before_filter :set_mobile_format

	def set_mobile_format
		request.format = :mobile unless request.format == :json
	end

	def load_layout
		params[:layout]=="true" ? "mobile_app" : false
	end

	
end

app/controllers/mobile_app/place_types_controller.rb
class MobileApp::PlaceTypesController < MobileApp::MobileController
  def index
  	@place_types = PlaceType.all
  end
end

app/controllers/mobile_app/places_controller.rb
class MobileApp::PlacesController < MobileApp::MobileController
	before_filter :load_type
  def index
  	print "\n!@type.nil? on index=>#{!@type.nil?}\n"
  	@places = !@type.nil? ? Place.actives.where(:place_type_id=>@type.id) : Place.all
  end

  def show      
		@place = Place.find_by_id(params[:id])
  end

  def load_type
  	@type = PlaceType.find_by_id(params[:place_type_id])
  	print "\n@type.nil?=>#{@type.nil?}\n"
  end

  def map
    @places = Place.places_for_map
    respond_to do |format|
      format.html
      format.mobile
      format.json{ render json: @places}
    end
  end

end

app/helpers/mobile_app/events_helper.rb
module MobileApp::EventsHelper
	def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).calendar_with_header
  end

  def calendar_weeks(date = Date.today, &block)
    Calendar.new(self, date, block).week_rows
  end

  def new_calendar(date = Date.today, &block)
    Calendar.new(self, date, block)
  end


  def link_for_event
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER_SHORT = %w[Dom Lun Mar Mie Jue Vie Sab]
    HEADER_LONG = %w[Domingo Lunes Martes Miercoles Jueves Viernes Sabado]
    START_DAY = :sunday

    delegate :content_tag, :link_to, :mobile_app_events_url ,to: :view

    def calendar_with_header
    	content_tag :div, class: "calendar-body" do
    		table_with_headers
    	end
    end

    def table_with_headers
      content_tag :table, class: "calendar-days" do
        table_headers + table_body
      end
    end

    def table_headers
      content_tag :thead do
        header_long + header_short
      end
    end

    def table_body
      content_tag :tbody, class: "week-rows", :id=>"week-rows" do
        week_rows
      end
    end

     def header_long
      content_tag :tr, class: "calendar-header calendar-header-long",:data=>{:role=>"header"} do
        HEADER_LONG.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def header_short
      content_tag :tr,class: "calendar-header calendar-header-short",:data=>{:role=>"header"} do
        HEADER_SHORT.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell_link(day)
      if day.month != date.month
        content_tag :div, class: "day-buttom" do
          view.capture(day, &callback)
        end
      else
        link_to "#events-date", :data=>{:backend=>mobile_app_events_url(:date_at=>day)}, :class=>"day-link backend-link" do
          content_tag :div, class: "day-buttom day-buttom-link" do
            view.capture(day, &callback)
          end
        end
      end
    end

    def day_cell(day)
        content_tag :td, class: day_classes(day) do
          day_cell_link(day)
        end
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/helpers/mobile_app/galleries_helper.rb
module MobileApp::GalleriesHelper
end

app/helpers/mobile_app/home_helper.rb
module MobileApp::HomeHelper
end

app/helpers/mobile_app/info_pages_helper.rb
module MobileApp::InfoPagesHelper
end

app/helpers/mobile_app/place_types_helper.rb
module MobileApp::PlaceTypesHelper
end

app/helpers/mobile_app/places_helper.rb
module MobileApp::PlacesHelper
end

app/views/mobile_app/events/_calendar.mobile.erb
<%=calendar_weeks @date_for_calendar do |date|%>
	<div class ="schedule">
		<%for i in 0..23 do%>
					<%case i%>
				<%when 0%>
					<div id="hour-range-<%=i%>" class= "hour-range hour-range-start <%="hour-range-selected" if !@events[date.day.to_i.to_s.to_sym].nil? and !@events[date.day.to_i.to_s.to_sym][i.to_s.to_sym].nil?%>">
					</div>
				<%when 23%>
					<div id="hour-range-<%=i%>" class= "hour-range hour-range-end <%="hour-range-selected" if !@events[date.day.to_i.to_s.to_sym].nil? and !@events[date.day.to_i.to_s.to_sym][i.to_s.to_sym].nil?%>">
					</div>
				<%else%>
				<div id="hour-range-<%=i%>" class= "hour-range <%="hour-range-selected" if !@events[date.day.to_i.to_s.to_sym].nil? and !@events[date.day.to_i.to_s.to_sym][i.to_s.to_sym].nil?%>">
				</div>
			<%end%>
		<%end%>
	</div>
	<div class = "day">
		<%=date.day%>
	</div>
<%end%>
<%=hidden_field_tag "prev-moth", @date_for_calendar.prev_month, :id=>"prev-month-hidden"%>
<%=hidden_field_tag "next-moth", @date_for_calendar.next_month, :id=>"next-month-hidden"%>
<%=hidden_field_tag "label-month", @date_for_calendar.strftime("%B %Y"), :id=>"label-month-hidden"%>

app/views/mobile_app/events/date_index.mobile.erb
<div data-role = "content" class= "page_content">
  <h2><%=@events.count%> Eventos programados para <%=@date_at.strftime("%A %e de %B")%></h2>
  <ul data-role="listview" data-theme="d" data-divider-theme="d">
    <%@events.each do |event|%>
      <li>
        <%=link_to "#events-show", :data=>{:backend=>mobile_app_event_url(:id=>event.id)}, :class=>"backend-link"  do%>
          <h3><%=event.name%></h3>
          <p><%=event.description%></p>
          <p class="ui-li-aside"><strong><%=event.start_at.strftime("%l:%m %p")%></strong></p>
        <%end%>
      </li>
    <%end%>
  </ul>
</div>

app/views/mobile_app/events/index.mobile.erb
<div id="calendar-content" data-role="content" class= "page_content">   
	<div id = "calendar">
		<div id = "calendar-header" class = "calendar-header" data-role="header" data-theme="a">
			<%= link_to "", "", :class=> "calendar-link", :id=>"prev-month", :data=>{:role=>"button",:icon=>"arrow-l",:iconpos=>"notext", :inline=>true,:month => @date_for_calendar.prev_month, :backend=> mobile_app_events_url(calendar: true)} %>
			<h2 id="month">
			    <%= @date_for_calendar.strftime("%B %Y") %>
			</h2>
			<%= link_to "","", :class=> "calendar-link", :id=>"next-month",:data=>{:role=>"button",:icon=>"arrow-r",:iconpos=>"notext", :inline=>true, :month=> @date_for_calendar.next_month, :backend=> mobile_app_events_url(calendar: true)}   %>
		</div>
		<%=calendar do |date|%>
			<div class ="schedule">
				<%for i in 0..23 do%>
					<%case i%>
						<%when 0%>
							<div id="hour-range-<%=i%>" class= "hour-range hour-range-start <%="hour-range-selected" if !@events[date.day.to_i.to_s.to_sym].nil? and !@events[date.day.to_i.to_s.to_sym][i.to_s.to_sym].nil?%>">
							</div>
						<%when 23%>
							<div id="hour-range-<%=i%>" class= "hour-range hour-range-end <%="hour-range-selected" if !@events[date.day.to_i.to_s.to_sym].nil? and !@events[date.day.to_i.to_s.to_sym][i.to_s.to_sym].nil?%>">
							</div>
						<%else%>
						<div id="hour-range-<%=i%>" class= "hour-range <%="hour-range-selected" if !@events[date.day.to_i.to_s.to_sym].nil? and !@events[date.day.to_i.to_s.to_sym][i.to_s.to_sym].nil?%>">
						</div>
					<%end%>
				<%end%>
			</div>
			<div class = "day">
				<%=date.day%>
			</div>
		<%end%>
	</div>
</div>


<div id = "events-content" data-role = "content" style="padding: 0px 15px;" class= "page_content" >
	<div id = "upcomming-header" class="upcomming-header" data-role="header" data-theme="a">
		<h2>Proximos eventos</h2>
	</div>
	<ul data-role="listview" data-theme="d" data-divider-theme="d" data-inset="true">
		<%@up_comming.each do |key,day_events|%>
			<li data-role="list-divider" data-role="collapsible"><%=day_events[0].start_at.strftime("%A %e de %B")%> <span class="ui-li-count"><%=day_events.count%></span></li>
			<%day_events.each do |event|%>
				<li>
        <%=link_to "#events-show", :data=>{:backend=>mobile_app_event_url(:id=>event.id)}, :class=>"backend-link"  do%>
						<h3><%=event.name%></h3>
						<p><%=event.description%></p>
						<p class="ui-li-aside"><strong><%=event.start_at.strftime("%l:%m %p")%></strong></p>
					<%end%>
				</li>
			<%end%>
		<%end%>
	</ul>
</div>

app/views/mobile_app/events/show.mobile.erb
<div data-role="content" class="page_content info-page-content" >        

  <center><h2><%=@event.name%></h2></center>
  <%=image_tag @event.flayer.url, :style=>"width:100%;height:auto;"%>

   <div>
    <p><strong>Fecha:</strong><br/><%=@event.start_at.strftime("%A %e de %B a las %l:%m %p")%></p>
  </div>     

  <div>
    <p><strong>Lugar:</strong><br/><%=@event.location%></p>
  </div>          
  
  <div>
    <p><strong>Acerca del evento:</strong><br/><%=@event.description%></p> 
  </div>    
  
  <img src="http://maps.google.com/maps/api/staticmap?zoom=<%=@event.zoom%>&amp;size=250x200&amp;maptype=roadmap&amp;markers=color:red|label:|<%=@event.latlng%>&amp;sensor=false" class="map">
  <div class="ui-grid-solo">
    <div class="ui-block-a"><%=link_to "Asistir", mobile_app_attend_event_path(:event_id=>@event.id, :format=>:json), :method => :post,:data=>{:role=>"button", :event=>@event.id}, :class=>"attend-btn" %></div>
  </div>
</div>